%% Example driver script for simulating "antithetic" model.
% This file was automatically generated by OneModel.
% Any changes you make to it will be overwritten the next time
% the file is generated.

clear all;
close all;

% Init model.
m = host_aware_antithetic_controller();

% Solver options.
opt = odeset('AbsTol',1e-8,'RelTol',1e-8);
opt = odeset(opt,'Mass',m.M);

% Base parameters.
p = m.p;
p.cell__nu = 1200;
p.cell__z1__omega = 1;
p.cell__z2__omega_max = 1;
p.cell__x__omega_max = 1;
p.cell__x__h = 0.001;

% Simulation neglecting the burden produced to the host.
p.cell____burden = 0;
out_no_host = simulate(m, opt, p);

% Simulation considering the burden produced to the host.
p.cell____burden = 1;
out_host = simulate(m, opt, p);


%% Plot results

fontSize = 8;
axisSize = 6;

f = figure('Position',[0,0,235,225]);
set(gca,'Fontsize',axisSize);

yyaxis left;
hold on;
ylabel('Protein $x$ $\; [$fg$]$','interpreter','latex','FontSize',fontSize);
ylim([0 100]);
plot(out_no_host.t, out_no_host.cell__x__m);
plot(out_host.t, out_host.cell__x__m);

yyaxis right;
hold on;
ylabel('Growth rate $\; [$min$^{-1}]$','interpreter','latex','FontSize',fontSize);
ylim([0 0.03]);
plot(out_no_host.t, out_no_host.cell__mu);
plot(out_host.t, out_host.cell__mu);
xlabel('Time $\; [h]$','interpreter','latex','FontSize',fontSize);


%% Simulation function

function [out] = simulate(m, opt, p)
% Parameters for steady state first simulation.
p_0 = p;
p_0.tspan = [0 100000];
p_0.cell__z1__omega = 0;
p_0.cell__z2__omega_max = 0;
p_0.cell__x__omega_max = 0;

% Parameters first step of the simulation.
p_1 = p;
p_1.tspan = [0 2]*60;
p_1.cell__z1__omega = 0;
p_1.cell__z2__omega = 0;

% Parameters second step of the simulation.
p_2 = p;
p_2.tspan = [p_1.tspan(2) p_1.tspan(2)+18*60];

% Simulate

% Previous simulation.
[t,x] = ode15s(@(t,x) m.ode(t,x,p_0),p_0.tspan,m.x0,opt);
out_0 = m.simout2struct(t,x,p_0);

% First simulation step.
[t,x] = ode15s(@(t,x) m.ode(t,x,p_1),p_1.tspan,x(end,:),opt);
out_1 = m.simout2struct(t,x,p_1);

% Second simulation step.
[t,x] = ode15s(@(t,x) m.ode(t,x,p_2),p_2.tspan,x(end,:),opt);
out_2 = m.simout2struct(t,x,p_2);

out = concatStruct(out_1, out_2);

out.t = out.t/60;
end