%% Example driver script for simulating "antithetic" model.
% This file was automatically generated by OneModel.
% Any changes you make to it will be overwritten the next time
% the file is generated.

clear all;
close all;

% Init model.
m = antithetic_controller();

% Solver options.
opt = odeset('AbsTol',1e-8,'RelTol',1e-8);
opt = odeset(opt,'Mass',m.M);

% Simulation time span.
tspan = [0 1000];

p = m.p;
p.cell__z1__omega = 0;
p.cell__z2__omega = 0;
p.cell__z12__omega = 0;

[t,x] = ode15s(@(t,x) m.ode(t,x,p),tspan,m.x0,opt);
out_1 = m.simout2struct(t,x,p);

tspan = [1000 m.opts.t_end+1000];
[t,x] = ode15s(@(t,x) m.ode(t,x,m.p),tspan,x(end,:),opt);
out_2 = m.simout2struct(t,x,m.p);

out = concatStruct(out_1, out_2);


% Plot result.
figure(1);

subplot(2,2,1);

hold on;
plot(out.t, out.cell__x__m);
plot(out.t, out.cell__ref);

grid on;
title('Output');
legend('x');

subplot(2,2,2);

hold on;
plot(out.t, out.cell__mu);

grid on;
title('Growth rate');
legend('\mu');

subplot(2,2,3);

hold on;
plot(out.t, out.cell__z1__m);
plot(out.t, out.cell__z2__m);
% plot(out.t, out.cell__z12__m);

grid on;
title('Control action');
legend('z1','z2','z12');

subplot(2,2,4);

hold on;
plot(out.t, out.cell__p_r__m);
plot(out.t, out.cell__p_nr__m);

grid on;
title('ribo and non-ribo');
legend('r','nr');

